language: scala

sudo: required

jdk:
- openjdk8
- openjdk11

scala:
- 2.11.12
- 2.12.9
- 2.13.0

cache:
  directories:
  - $HOME/.sbt/1.0/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.cache/coursier/v1
  - $HOME/.nvm

addons:
  apt:
    packages:
    - graphviz

before_install:
- export PATH=${PATH}:./vendor/bundle
- git fetch --tags

script:
- sbt ++$TRAVIS_SCALA_VERSION! test

stages:
- name: test
- name: release
  if: (branch = master AND type = push) OR (tag IS present) AND NOT fork

jobs:
  include:
  - stage: release
    script: sbt ci-release

branches:
  only:
    - master
    - /v.+/