addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "1.0.0")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "1.0.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "0.6.33")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"                    % "5.6.0")
addSbtPlugin("com.dwijnand"       % "sbt-travisci"                  % "1.2.0")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release"                % "1.5.10")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"                  % "2.4.2")
